#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit 0" INT


export NEXTCLADE_BIN="${1:? "Usage: ${0} <path_to_nextclade> <path_to_datasets_collection_dir>"}"
export INPUT_DATASETS_DIR="${2:? "Usage: ${0} <path_to_nextclade> <path_to_datasets_collection_dir>"}"
export NEXTCLADE_BIN

THIS_DIR=$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd
)
export THIS_DIR

export OUT_DIR="$THIS_DIR/../tmp_v3/smoke-tests/result"


function run_with_dataset_dir() {
  name="${1}"
  dataset_dir="${2}"
  sequences="${3}"
  out_dir="${OUT_DIR}/${name}/with_dataset"

  ${NEXTCLADE_BIN} run --quiet --in-order --include-reference \
    --input-dataset="${dataset_dir}" \
    --output-translations="${out_dir}/translations/gene_{gene}.translation.fasta" \
    --output-all="${out_dir}" \
    "${sequences}"
}
export -f run_with_dataset_dir


function run_with_dataset_zip() {
  name="${1}"
  dataset_dir="${2}"
  sequences="${3}"
  out_dir="${OUT_DIR}/${name}/with_dataset"

  ${NEXTCLADE_BIN} run --quiet --in-order --include-reference \
    --input-dataset="${dataset_dir}/dataset.zip" \
    --output-translations="${out_dir}/translations/gene_{gene}.translation.fasta" \
    --output-all="${out_dir}" \
    "${sequences}"
}
export -f run_with_dataset_zip


function run_with_ref_only() {
  name="${1}"
  dataset_dir="${2}"
  sequences="${3}"
  out_dir="${OUT_DIR}/${name}/with_ref_only"

  ${NEXTCLADE_BIN} run --quiet --in-order --include-reference \
    --input-ref="${dataset_dir}/reference.fasta" \
    --output-translations="${out_dir}/translations/gene_{gene}.translation.fasta" \
    --output-all="${out_dir}" \
    "${sequences}"
}
export -f run_with_ref_only


function run_with_ref_and_annotation() {
  name="${1}"
  dataset_dir="${2}"
  sequences="${3}"
  out_dir="${OUT_DIR}/${name}/with_ref_and_annotation"

  if [ ! -f "${dataset_dir}/genome_annotation.gff3" ]; then return; fi

  ${NEXTCLADE_BIN} run --quiet --in-order --include-reference \
    --input-ref="${dataset_dir}/reference.fasta" \
    --input-gene-map="${dataset_dir}/genome_annotation.gff3" \
    --output-translations="${out_dir}/translations/gene_{gene}.translation.fasta" \
    --output-all="${out_dir}" \
    "${sequences}"
}
export -f run_with_ref_and_annotation


function run_with_ref_and_tree() {
  name="${1}"
  dataset_dir="${2}"
  sequences="${3}"
  out_dir="${OUT_DIR}/${name}/with_ref_and_tree"

  if [ ! -f "${dataset_dir}/tree.json" ]; then return; fi

  ${NEXTCLADE_BIN} run --quiet --in-order --include-reference \
    --input-ref="${dataset_dir}/reference.fasta" \
    --input-tree="${dataset_dir}/tree.json" \
    --output-translations="${out_dir}/translations/gene_{gene}.translation.fasta" \
    --output-all="${out_dir}" \
    "${sequences}"
}
export -f run_with_ref_and_tree


function run_with_ref_and_annotation_and_tree() {
  name="${1}"
  dataset_dir="${2}"
  sequences="${3}"
  out_dir="${OUT_DIR}/${name}/with_ref_and_annotation_and_tree"

  if [ ! -f "${dataset_dir}/genome_annotation.gff3" ]; then return; fi
  if [ ! -f "${dataset_dir}/tree.json" ]; then return; fi

  ${NEXTCLADE_BIN} run --quiet --in-order --include-reference \
    --input-ref="${dataset_dir}/reference.fasta" \
    --input-gene-map="${dataset_dir}/genome_annotation.gff3" \
    --input-tree="${dataset_dir}/tree.json" \
    --output-translations="${out_dir}/translations/gene_{gene}.translation.fasta" \
    --output-all="${out_dir}" \
    "${sequences}"
}
export -f run_with_ref_and_annotation_and_tree


function run_single_dataset() {
  dataset_dir=$1
  name="$(realpath --relative-to="$INPUT_DATASETS_DIR" "$dataset_dir")"

  # This dataset is crashing, probably due to defective or unsupported features
  if [[ "$name" =~ vic_na* ]]; then
    return
  fi

  # This dataset is crashing, due to a defect in the dataset
  if [[ "$name" == sars-cov-2-21L* ]]; then
    return
  fi

  # This dataset is crashing, due to a defect in the dataset's genome annotation
  if [[ "$name" == flu/h3n2/ha* ]]; then
    return
  fi

  sequences="$dataset_dir/sequences.fasta"
  msg_no_sequences=""
  if [ ! -f "${sequences}" ]; then
    sequences="$dataset_dir/reference.fasta"
    msg_no_sequences=" (Note: this dataset contains no example sequences. Using reference sequence as query.)"
  fi

  echo "Running '${NEXTCLADE_BIN}' for '${name}'${msg_no_sequences}"

  run_with_dataset_dir                    "${name}" "${dataset_dir}" "${sequences}"
  run_with_dataset_zip                    "${name}" "${dataset_dir}" "${sequences}"
  run_with_ref_only                       "${name}" "${dataset_dir}" "${sequences}"
  run_with_ref_and_annotation             "${name}" "${dataset_dir}" "${sequences}"
  run_with_ref_and_tree                   "${name}" "${dataset_dir}" "${sequences}"
  run_with_ref_and_annotation_and_tree    "${name}" "${dataset_dir}" "${sequences}"
}
export -f run_single_dataset

find "${INPUT_DATASETS_DIR}" -iname "pathogen.json" -exec dirname '{}' \; |
  parallel --keep-order --jobs=+0 run_single_dataset
