#!/usr/bin/env bash

#
# Run nextclade on different Linux distros
#

set -euo pipefail
trap "exit 0" INT

function abspath() {
  readlink -m "$1"
}

NEXTCLADE_BIN="${1:-$(pwd)/.out/nextclade-x86_64-unknown-linux-gnu}"

VOLUME="$(abspath "${NEXTCLADE_BIN}"):/nextclade"

RUN_COMMAND="/nextclade dataset list >/dev/null"

for distro in \
  "debian:7.3" \
  "debian:8.0" \
  "debian:9.0" \
  "debian:10.0" \
  "debian:11.0" \
  "debian:stable" \
  "debian:testing" \
  "debian:sid" \
  "debian:latest" \
  "ubuntu:16.04" \
  "ubuntu:18.04" \
  "ubuntu:20.04" \
  "ubuntu:22.04" \
  "ubuntu:latest"; do
  docker pull -q "$distro" >/dev/null
  echo "$distro"
  docker run -it --rm -v "${VOLUME}" "$distro" bash -c "${RUN_COMMAND}" || true
  echo ""
done

for distro in \
  "amazonlinux:2017.12.0.20171212.2" \
  "amazonlinux:2.0.20180622.1" \
  "amazonlinux:2.0.20190115" \
  "amazonlinux:2.0.20191217.0" \
  "amazonlinux:2.0.20200207.1" \
  "amazonlinux:2.0.20210126.0" \
  "amazonlinux:2.0.20220121.0" \
  "amazonlinux:latest" \
  "centos:7.2.1511" \
  "centos:7.5.1804" \
  "centos:8.1.1911" \
  "centos:8.4.2105" \
  "centos:latest" \
  "fedora:27" \
  "fedora:30" \
  "fedora:33" \
  "fedora:36" \
  "fedora:latest" \
  "oraclelinux:7.2" \
  "oraclelinux:8.0" \
  "oraclelinux:8.6" \
  "registry.access.redhat.com/ubi7/ubi" \
  "registry.access.redhat.com/ubi8/ubi" \
  "registry.access.redhat.com/ubi9/ubi"; do
  docker pull -q "$distro" >/dev/null
  echo "$distro"
  docker run -it --rm -v "${VOLUME}" "$distro" bash -c "${RUN_COMMAND}" || true
  echo ""
done

for distro in \
  "opensuse/archive:13.2" \
  "opensuse/leap:15.2" \
  "opensuse/tumbleweed:latest"; do
  docker pull -q "$distro" >/dev/null
  echo "$distro"
  docker run -it --rm -v "${VOLUME}" "$distro" bash -c "${RUN_COMMAND}" || true
  echo ""
done

for distro in \
  "archlinux:latest"; do
  docker pull -q "$distro" >/dev/null
  echo "$distro"
  docker run -it --rm -v "${VOLUME}" "$distro" bash -c "${RUN_COMMAND}" || true
  echo ""
done
