use crate::align::params::AlignPairwiseParams;
use crate::alphabet::aa::Aa;
use crate::alphabet::letter::{serde_deserialize_seq, serde_serialize_seq};
use crate::alphabet::nuc::Nuc;
use crate::gene::cds::Cds;
use serde::{Deserialize, Serialize};

pub const fn decode(triplet: &[Nuc]) -> Aa {
  match *triplet {
    [Nuc::Gap, Nuc::Gap, Nuc::Gap] => Aa::Gap,
    [Nuc::A, Nuc::A, Nuc::A] => Aa::K,
    [Nuc::A, Nuc::A, Nuc::C] => Aa::N,
    [Nuc::A, Nuc::A, Nuc::G] => Aa::K,
    [Nuc::A, Nuc::A, Nuc::R] => Aa::K,
    [Nuc::A, Nuc::A, Nuc::T] => Aa::N,
    [Nuc::A, Nuc::A, Nuc::Y] => Aa::N,
    [Nuc::A, Nuc::C, Nuc::A] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::B] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::C] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::D] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::G] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::H] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::K] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::M] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::N] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::R] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::S] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::T] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::V] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::W] => Aa::T,
    [Nuc::A, Nuc::C, Nuc::Y] => Aa::T,
    [Nuc::A, Nuc::G, Nuc::A] => Aa::R,
    [Nuc::A, Nuc::G, Nuc::C] => Aa::S,
    [Nuc::A, Nuc::G, Nuc::G] => Aa::R,
    [Nuc::A, Nuc::G, Nuc::R] => Aa::R,
    [Nuc::A, Nuc::G, Nuc::T] => Aa::S,
    [Nuc::A, Nuc::G, Nuc::Y] => Aa::S,
    [Nuc::A, Nuc::T, Nuc::A] => Aa::I,
    [Nuc::A, Nuc::T, Nuc::C] => Aa::I,
    [Nuc::A, Nuc::T, Nuc::G] => Aa::M,
    [Nuc::A, Nuc::T, Nuc::H] => Aa::I,
    [Nuc::A, Nuc::T, Nuc::M] => Aa::I,
    [Nuc::A, Nuc::T, Nuc::T] => Aa::I,
    [Nuc::A, Nuc::T, Nuc::W] => Aa::I,
    [Nuc::A, Nuc::T, Nuc::Y] => Aa::I,
    [Nuc::C, Nuc::A, Nuc::A] => Aa::Q,
    [Nuc::C, Nuc::A, Nuc::C] => Aa::H,
    [Nuc::C, Nuc::A, Nuc::G] => Aa::Q,
    [Nuc::C, Nuc::A, Nuc::R] => Aa::Q,
    [Nuc::C, Nuc::A, Nuc::T] => Aa::H,
    [Nuc::C, Nuc::A, Nuc::Y] => Aa::H,
    [Nuc::C, Nuc::C, Nuc::A] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::B] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::C] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::D] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::G] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::H] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::K] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::M] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::N] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::R] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::S] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::T] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::V] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::W] => Aa::P,
    [Nuc::C, Nuc::C, Nuc::Y] => Aa::P,
    [Nuc::C, Nuc::G, Nuc::A] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::B] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::C] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::D] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::G] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::H] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::K] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::M] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::N] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::R] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::S] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::T] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::V] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::W] => Aa::R,
    [Nuc::C, Nuc::G, Nuc::Y] => Aa::R,
    [Nuc::C, Nuc::T, Nuc::A] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::B] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::C] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::D] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::G] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::H] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::K] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::M] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::N] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::R] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::S] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::T] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::V] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::W] => Aa::L,
    [Nuc::C, Nuc::T, Nuc::Y] => Aa::L,
    [Nuc::G, Nuc::A, Nuc::A] => Aa::E,
    [Nuc::G, Nuc::A, Nuc::C] => Aa::D,
    [Nuc::G, Nuc::A, Nuc::G] => Aa::E,
    [Nuc::G, Nuc::A, Nuc::R] => Aa::E,
    [Nuc::G, Nuc::A, Nuc::T] => Aa::D,
    [Nuc::G, Nuc::A, Nuc::Y] => Aa::D,
    [Nuc::G, Nuc::C, Nuc::A] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::B] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::C] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::D] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::G] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::H] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::K] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::M] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::N] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::R] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::S] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::T] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::V] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::W] => Aa::A,
    [Nuc::G, Nuc::C, Nuc::Y] => Aa::A,
    [Nuc::G, Nuc::G, Nuc::A] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::B] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::C] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::D] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::G] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::H] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::K] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::M] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::N] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::R] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::S] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::T] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::V] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::W] => Aa::G,
    [Nuc::G, Nuc::G, Nuc::Y] => Aa::G,
    [Nuc::G, Nuc::T, Nuc::A] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::B] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::C] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::D] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::G] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::H] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::K] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::M] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::N] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::R] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::S] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::T] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::V] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::W] => Aa::V,
    [Nuc::G, Nuc::T, Nuc::Y] => Aa::V,
    [Nuc::M, Nuc::G, Nuc::A] => Aa::R,
    [Nuc::M, Nuc::G, Nuc::G] => Aa::R,
    [Nuc::M, Nuc::G, Nuc::R] => Aa::R,
    [Nuc::T, Nuc::A, Nuc::A] => Aa::Stop,
    [Nuc::T, Nuc::A, Nuc::C] => Aa::Y,
    [Nuc::T, Nuc::A, Nuc::G] => Aa::Stop,
    [Nuc::T, Nuc::A, Nuc::R] => Aa::Stop,
    [Nuc::T, Nuc::A, Nuc::T] => Aa::Y,
    [Nuc::T, Nuc::A, Nuc::Y] => Aa::Y,
    [Nuc::T, Nuc::C, Nuc::A] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::B] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::C] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::D] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::G] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::H] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::K] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::M] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::N] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::R] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::S] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::T] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::V] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::W] => Aa::S,
    [Nuc::T, Nuc::C, Nuc::Y] => Aa::S,
    [Nuc::T, Nuc::G, Nuc::A] => Aa::Stop,
    [Nuc::T, Nuc::G, Nuc::C] => Aa::C,
    [Nuc::T, Nuc::G, Nuc::G] => Aa::W,
    [Nuc::T, Nuc::G, Nuc::T] => Aa::C,
    [Nuc::T, Nuc::G, Nuc::Y] => Aa::C,
    [Nuc::T, Nuc::R, Nuc::A] => Aa::Stop,
    [Nuc::T, Nuc::T, Nuc::A] => Aa::L,
    [Nuc::T, Nuc::T, Nuc::C] => Aa::F,
    [Nuc::T, Nuc::T, Nuc::G] => Aa::L,
    [Nuc::T, Nuc::T, Nuc::R] => Aa::L,
    [Nuc::T, Nuc::T, Nuc::T] => Aa::F,
    [Nuc::T, Nuc::T, Nuc::Y] => Aa::F,
    [Nuc::Y, Nuc::T, Nuc::A] => Aa::L,
    [Nuc::Y, Nuc::T, Nuc::G] => Aa::L,
    [Nuc::Y, Nuc::T, Nuc::R] => Aa::L,
    _ => Aa::X,
  }
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct CdsPeptide {
  pub name: String,

  #[schemars(with = "String")]
  #[serde(serialize_with = "serde_serialize_seq")]
  #[serde(deserialize_with = "serde_deserialize_seq")]
  pub seq: Vec<Aa>,
}

/// Translates a nucleotide sequence of a gene into the corresponding aminoacid sequence (peptide)
pub fn translate(gene_nuc_seq: &[Nuc], cds: &Cds, params: &AlignPairwiseParams) -> CdsPeptide {
  // NOTE: rounds the result to the multiple of 3 (floor) so that translation does not overrun the buffer
  let peptide_length = gene_nuc_seq.len() / 3;

  let mut peptide = Vec::<Aa>::with_capacity(peptide_length);
  for i_aa in 0..peptide_length {
    let i_nuc = i_aa * 3;
    let triplet: &[Nuc] = &gene_nuc_seq[i_nuc..(i_nuc + 3)];
    let aminoacid = decode(triplet);
    peptide.push(aminoacid);
    if params.no_translate_past_stop && aminoacid == Aa::Stop {
      break;
    }
  }
  peptide.shrink_to_fit();

  CdsPeptide {
    name: cds.name.clone(),
    seq: peptide,
  }
}
