/**
 * Generate Typescript types from JSON schema
 */
import { readFile, writeFile } from 'fs-extra'
import { basename, dirname } from 'path'
import yaml from 'js-yaml'
import { Command } from 'commander'
import { compile } from 'json-schema-to-typescript'
import prettier from 'prettier'

async function main() {
  const args = new Command()
    .description('Generate Typescript types from JSON schema')
    .requiredOption('-i, --input <input.schema.json|yml>', 'Input JSON schema')
    .requiredOption('-o, --output <output.d.ts>', 'Output Typescript typings')
    .parse(process.argv)
    .opts()

  const schema = yaml.load((await readFile(args.input)).toString('utf8'))

  const thisScriptName = basename(__filename)

  let code = await compile(schema, 'schema', {
    cwd: dirname(args.input),
    bannerComment: `// *** AUTOGENERATED! DO NOT EDIT! All modifications to this file will be overwritten!\n// *** This file is autogenerated by script '${thisScriptName}' from JSON schema specified in '${args.input}'.`,
    format: true,
    additionalProperties: false,
    enableConstEnums: true,
    declareExternallyReferenced: true,
    strictIndexSignatures: false,
  })

  code = code.replaceAll(/\?: (\w+) \| null;/g, '?: $1')
  code = await prettier.format(code, { parser: 'typescript' })
  await writeFile(args.output, code)
}

main().catch(console.error)
