use eyre::Report;
use nextclade::analyze::pcr_primers::PcrPrimer;
use nextclade::analyze::virus_properties::{PhenotypeAttrDesc, VirusProperties};
use nextclade::gene::gene_map::GeneMap;
use nextclade::io::dataset::{DatasetTagJson, DatasetsIndexJson};
use nextclade::io::errors_csv::ErrorsFromWeb;
use nextclade::io::fasta::FastaRecord;
use nextclade::io::file::create_file_or_stdout;
use nextclade::io::fs::ensure_dir;
use nextclade::io::json::json_write_impl;
use nextclade::io::nextclade_csv::CsvColumnConfig;
use nextclade::qc::qc_config::QcConfig;
use nextclade::qc::qc_run::QcResult;
use nextclade::run::nextclade_wasm::{
  AnalysisInitialData, AnalysisInput, NextcladeResult, NextcladeParams, NextcladeParamsRaw,
};
use nextclade::translate::translate_genes::Translation;
use nextclade::tree::tree::{AuspiceTree, CladeNodeAttrKeyDesc};
use nextclade::types::outputs::{NextcladeErrorOutputs, NextcladeOutputs};
use schemars::{schema_for, JsonSchema};
use std::path::Path;

const OUTPUT_JSON_SCHEMA: &str = "src/gen/_SchemaRoot.json";

fn main() -> Result<(), Report> {
  ensure_dir(OUTPUT_JSON_SCHEMA)?;
  write_jsonschema::<_SchemaRoot>(OUTPUT_JSON_SCHEMA)?;
  Ok(())
}

/// Create JSON schema file from a given Rust struct type and write it to a specified file.
fn write_jsonschema<T: JsonSchema>(output_file: impl AsRef<Path>) -> Result<(), Report> {
  let schema = schema_for!(T);
  json_write_impl(create_file_or_stdout(output_file)?, &schema)
}

// Dummy struct containing the types we want to expose (recursively).
//
// The doc comment below will appear in the schema file. Schema file should not be edited manually. But despite this
// comment also being here, you CAN edit this struct. Go ahead!
//
/// AUTOGENERATED! DO NOT EDIT! This JSON schema file is generated automatically from Rust types.
/// The topmost schema definition is a dummy container for the types we want to expose. Disregard
/// it. Instead, See the actual types in the `definitions` property of JSON schema.
#[derive(Clone, Debug, JsonSchema)]
#[serde(rename_all = "camelCase")]
struct _SchemaRoot {
  _1: GeneMap,
  _2: Translation,
  _3: AuspiceTree,
  _4: QcConfig,
  _5: QcResult,
  _6: PcrPrimer,
  _7: NextcladeOutputs,
  _8: DatasetsIndexJson,
  _9: CsvColumnConfig,
  _10: NextcladeErrorOutputs,
  _11: ErrorsFromWeb,
  _12: VirusProperties,
  _13: CladeNodeAttrKeyDesc,
  _14: PhenotypeAttrDesc,
  _15: FastaRecord,
  _16: DatasetTagJson,
  _17: AnalysisInitialData,
  _18: AnalysisInput,
  _19: NextcladeResult,
  _21: NextcladeParams,
  _22: NextcladeParamsRaw,
}
